language: python
python:
    - '3.9'

install:
    - pip install -r requirements-dev.txt

env:
    - PYTHONPATH=/home/travis/build/jasonzhagui/Scribble

script:
    - make tests

# deploy to heroku on push to master
deploy:
    - provider: heroku
    api_key: $HEROKU_API_KEY
    app: scribble-art
    on:
    branch: master